Updates for admin interface routing metric for pass OIM nodes

diff --git a/discovery/roles/postscripts/common/templates/omnia_oim_ha_node.j2 b/discovery/roles/postscripts/common/templates/omnia_oim_ha_node.j2
--- a/discovery/roles/postscripts/common/templates/omnia_oim_ha_node.j2
+++ b/discovery/roles/postscripts/common/templates/omnia_oim_ha_node.j2
@@ -45,7 +45,7 @@ if ! ifconfig | grep -w {{ hostvars['omnia_provision']['admin_nic'] }}; then
     done
 
     if [ -z "$INTERFACE" ]; then
-        echo "ERROR:: No admin interface found." >> "$LOGFILE"
+        echo "ERROR: No admin interface found." >> "$LOGFILE"
         exit 1
     fi
 
@@ -54,12 +54,19 @@ if ! ifconfig | grep -w {{ hostvars['omnia_provision']['admin_nic'] }}; then
     # 70-persistent-net.rules must be used as the file for consistent interface naming
     [ -f {{ persistent_rules_file }} ] || touch {{ persistent_rules_file }}
     echo "SUBSYSTEM==\"net\",ACTION==\"add\",ATTR{address}==\"${MAC}\",ATTR{type}==\"${TYPE}\",NAME=\"{{ hostvars['omnia_provision']['admin_nic'] }}\"" >> {{ persistent_rules_file }}
-    CONNECTION_PROFILE=$(nmcli -f name,device connection show | grep -w ${INTERFACE} | cut -d' ' -f1)
+    CONNECTION_PROFILE=$(nmcli -f name,device connection show | grep -w ${INTERFACE} | head -1 |cut -d' ' -f1)
     nmcli connection modify ${CONNECTION_PROFILE} connection.interface-name ""
     nmcli connection modify ${CONNECTION_PROFILE} match.interface-name {{ hostvars['omnia_provision']['admin_nic'] }} || { echo "ERROR: Using nmcli to match the interface name." >> "$LOGFILE"; exit 1; }
 
     echo "INFO: Renamed the admin interface to {{ hostvars['omnia_provision']['admin_nic'] }}." >> "$LOGFILE"
+
+else
+    CONNECTION_PROFILE=$(nmcli -f name,device connection show | grep -w {{ hostvars['omnia_provision']['admin_nic'] }} | head -1 | cut -d' ' -f1)
 fi
+
+nmcli connection modify ${CONNECTION_PROFILE} ipv4.route-metric 1 || { echo "ERROR: Using nmcli to update the admin interface's metric." >> "$LOGFILE"; exit 1; }
+
+echo "INFO: Updated the admin interface's metric to 1." >> "$LOGFILE"
 
 echo "$(date) - INFO - Finished OIM HA Post Script." >> "$LOGFILE"
 echo "---------------------------"
