Update for Roce Thor2 chnages - 232.1.133.2

diff --git a/discovery/roles/postscripts/ubuntu/templates/omnia_roce.j2 b/discovery/roles/postscripts/ubuntu/templates/omnia_roce.j2
--- a/discovery/roles/postscripts/ubuntu/templates/omnia_roce.j2
+++ b/discovery/roles/postscripts/ubuntu/templates/omnia_roce.j2
@@ -5,12 +5,29 @@
 #
 #################################################################################################################
 echo "---------------------------"
+LOG_FILE="/var/log/xcat/xcat.log"
 
-echo "Checking for Broadcom NetXtreme-E cards" >> /var/log/xcat/xcat.log
+install_deb_files() {
+    local file=$1
+
+    if [[ -f "$file" ]]; then
+        echo "Installing $file" >> "$LOG_FILE"
+        sudo apt install -y "$file" >> "$LOG_FILE" 2>&1
+        if [[ $? -eq 0 ]]; then
+            echo "Successfully installed $file" >> "$LOG_FILE"
+        else
+            echo "Failed to install $file" >> "$LOG_FILE"
+        fi
+    else
+        echo "File $file not found" >> "$LOG_FILE"
+    fi
+}
+
+echo "Checking for Broadcom NetXtreme-E cards" >> $LOG_FILE
 thor_check=$(lspci -vvv 2>/dev/null | grep -i -E "BCM5750|BCM5760")
 if [[ -n $thor_check ]]
 then
-    echo "starting RoCE Installation" >> /var/log/xcat/xcat.log
+    echo "starting RoCE Installation" >> $LOG_FILE
     # Download the roce_src tar file
     wget --quiet --show-progress "http://{{ admin_nic_ip }}:80/install{{ repo_store_path }}/cluster/tarball/{{ roce_package_name }}"
     # Extract the contents of the tar file
@@ -19,16 +36,16 @@ then
 
     OS_VERSION=$(lsb_release -ds | cut -d ' ' -f 2)
     OS_VERSION_MAJOR=$(lsb_release -rs)
-    echo "OS VERSION: '$OS_VERSION'" >> /var/log/xcat/xcat.log
+    echo "OS VERSION: '$OS_VERSION'" >> $LOG_FILE
 
     ROCE_VERSION=$(echo "$extracted_driver_name" | grep -oP '\d+' | head -n 1)
-    echo "RoCE Major Version: $ROCE_VERSION" >> /var/log/xcat/xcat.log
+    echo "RoCE Major Version: $ROCE_VERSION" >> $LOG_FILE
 
     # install the L2, RoCE, and Peer Memory Direct (GPU direct) drivers
-    echo "starting RoCE netxtreme-peer-mem-dkms Installation" >> /var/log/xcat/xcat.log
+    echo "starting RoCE netxtreme-peer-mem-dkms Installation" >> $LOG_FILE
 
     # Search for .deb files using full OS version
-    echo "Searching for files matching OS version: $OS_VERSION" >> /var/log/xcat/xcat.log
+    echo "Searching for files matching OS version: $OS_VERSION" >> $LOG_FILE
     FILES=$(find ./$extracted_driver_name/ -wholename ".*$OS_VERSION*/netxtreme-peer-mem-dkms*.deb")
 
     # If files are found for the full OS version, move to RoCE version check
@@ -61,22 +78,30 @@ then
 
         # If a matching file is found, install it
         if [[ -n $MATCHED_FILE ]]; then
-            echo "Installing RoCE - $ROCE_VERSION match : $MATCHED_FILE" >> /var/log/xcat/xcat.log
-            sudo apt install -y "$MATCHED_FILE"
+            echo "Installing RoCE - $ROCE_VERSION match : $MATCHED_FILE" >> $LOG_FILE
+            install_deb_files "$MATCHED_FILE"
             echo "Completed Installation Process."
         else
-            echo "No netxtreme-peer-mem-dkms debian file found matching ROCE version $ROCE_VERSION ." >> /var/log/xcat/xcat.log
-            echo "Installing all : $FILES" >> /var/log/xcat/xcat.log
+            echo "No netxtreme-peer-mem-dkms debian file found matching ROCE version $ROCE_VERSION ." >> $LOG_FILE
+            echo "Installing all : $FILES" >> $LOG_FILE
             for file in $FILES; do
-                sudo apt install -y "$file"
+                install_deb_files -y "$file"
             done
         fi
-        echo "Completed RoCE netxtreme-peer-mem-dkms Installation" >> /var/log/xcat/xcat.log
+        echo "Completed RoCE netxtreme-peer-mem-dkms Installation" >> $LOG_FILE
     else
-        echo -e "RoCE installation failed. \n Exiting as no debian files found for netxtreme-peer-mem-dkms criteria." >> /var/log/xcat/xcat.log
+        echo -e "RoCE installation failed. \n Exiting as no debian files found for netxtreme-peer-mem-dkms criteria." >> $LOG_FILE
         exit 1
     fi
 
+    # Installing bnxt_re_conf and niccli
+    echo "Searching for bnxt_re_conf with RoCE version $ROCE_VERSION" >> "$LOG_FILE"
+    BNXT_RE_CONF_FILES=$(find "./$extracted_driver_name/" -type f -name "bnxt_re_conf_${ROCE_VERSION}*.deb" | head -n 1)
+    install_deb_files "$BNXT_RE_CONF_FILES"
+
+    echo "Searching for niccli with RoCE version $ROCE_VERSION" >> "$LOG_FILE"
+    NICCLI_FILES=$(find "./$extracted_driver_name/" -type f -name "niccli_${ROCE_VERSION}*.deb" | head -n 1)
+    install_deb_files "$NICCLI_FILES"
 
     # Download the roce_Drivers tar file
     sudo apt install -y linux-headers-"$(uname -r)"
@@ -98,7 +123,7 @@ then
             fi
         ' {} \;
         # compile and install the RoCE library
-        echo "Installing RoCE library" >> /var/log/xcat/xcat.log
+        echo "Installing RoCE library" >> $LOG_FILE
 
         find ./$extracted_source_name/ -name "*libbnxt_re*.tar.*" -exec sh -c '
             # Extract the tar file
@@ -119,8 +144,8 @@ then
         ' {} \;
         find /usr/lib64/ /usr/lib -name "libbnxt_re-rdmav*.so" -exec mv {} {}.inbox \;
     fi
-    echo "RoCE Installation completed" >> /var/log/xcat/xcat.log
+    echo "RoCE Installation completed" >> $LOG_FILE
 else
-    echo "Broadcom NetXtreme-E cards not found" >> /var/log/xcat/xcat.log
+    echo "Broadcom NetXtreme-E cards not found" >> $LOG_FILE
 fi
 echo "-----------------------------"
